<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">addLog4j2Configuration</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required configFilePathname</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFNYXAgcGlwZU1hcCA9IG5ldyBJRGF0YU1hcChwaXBlbGluZSk7DQoNClN0cmluZyBjb25m
aWdGaWxlUGF0aG5hbWUgPSBwaXBlTWFwLmdldEFzU3RyaW5nKCJjb25maWdGaWxlUGF0aG5hbWUi
KTsNClN0cmluZyBuYW1lID0gY29uZmlnRmlsZVBhdGhuYW1lLnJlcGxhY2UoIi4iLCAiIikucmVw
bGFjZSgiLyIsICIiKS4gcmVwbGFjZSgiXFwiLCAiIik7DQoNCkZpbGUgY29uZmlnRmlsZSA9IG5l
dyBGaWxlKGNvbmZpZ0ZpbGVQYXRobmFtZSk7DQoNCmlmIChjb25maWdGaWxlLmV4aXN0cygpICYm
IGNvbmZpZ0ZpbGUuY2FuUmVhZCgpKSB7DQoJdHJ5IHsNCiAgICAJTG9nZ2VyQ29udGV4dCBjb250
ZXh0ID0gbmV3IExvZ2dlckNvbnRleHQobmFtZSk7DQogICAgCQ0KICAgIAljb250ZXh0LnNldENv
bmZpZ0xvY2F0aW9uKGNvbmZpZ0ZpbGUudG9VUkkoKSk7DQogICAgCQ0KICAgIAlNYXA8U3RyaW5n
LCBMb2dnZXJDb25maWc+IGxvZ2dlcnMgPSBjb250ZXh0LmdldENvbmZpZ3VyYXRpb24oKS5nZXRM
b2dnZXJzKCk7DQogICAgCVNldDxTdHJpbmc+IGVudHJpZXMgPSBsb2dnZXJzLmtleVNldCgpOw0K
ICAgIAlmb3IgKFN0cmluZyBlbnRyeSA6IGVudHJpZXMpIHsNCgkJCWxvZ2dlckNvbnRleHRzTWFw
LnB1dChlbnRyeSwgY29udGV4dCk7DQoJCQlMb2dnZXIgbG9nZ2VyID0gY29udGV4dC5nZXRMb2dn
ZXIoZW50cnkpOw0KCQkJbG9nZ2VyTWFwLnB1dChlbnRyeSwgbG9nZ2VyKTsNCgkJCWxvZ0ludGVy
bmFsbHkoIkxvZ2dlciAiICsgZW50cnkgKyAiIGluaXRpYWxpemVkIiwgTGV2ZWwuSU5GTyk7DQoJ
CX0NCiAgICAJbG9nSW50ZXJuYWxseSgiQ29uZmlnIGZpbGUgIiArIGNvbmZpZ0ZpbGVQYXRobmFt
ZSArICIgaW5pdGlhbGl6ZWQiLCBMZXZlbC5JTkZPKTsNCgl9IGNhdGNoIChFeGNlcHRpb24gZSkg
ew0KCQlsb2dJbnRlcm5hbGx5KCJJbml0aWFsaXphdGlvbiBmYWlsZWQgZm9yICIgKyBuYW1lICsi
OiAiICsgZS5nZXRMb2NhbGl6ZWRNZXNzYWdlKCksIExldmVsLkVSUk9SKTsNCgl9DQp9IGVsc2Ug
ew0KCWxvZ0ludGVybmFsbHkoIkNvbmZpZyBmaWxlICIgKyBjb25maWdGaWxlUGF0aG5hbWUgKyAi
IGRvZXMgbm90IGV4aXN0IiwgTGV2ZWwuRVJST1IpOw0KfQ0KCQ0K</value>
</Values>
